Repository codestates-seb/seb42_main_001, pull requests merged in 2023-03, with the labels that each got.

#171 [FE] design: Drinks, Article Page 모바일 반응형 CSS 수정
  client/src/components/Article/ArticleDetail/articledetailcontent/ArticleDetailBody.tsx
  client/src/components/Drinks/DrinksDetail/drinksdetaillitem/DrinksDetailImg.tsx
  client/src/components/Drinks/DrinksDetail/drinksdetaillitem/drinksdetailtxt/DrinksDetailTitle.tsx
  client/src/components/Drinks/DrinksDetail/drinksdetaillitem/drinksdetailtxt/drinksdetailbox/DrinksDetailTags.tsx
  client/src/components/Drinks/DrinksList/drinkscontent/DrinksItem.tsx
  client/src/components/Drinks/DrinksList/drinkscontent/drinksitem/DrinksItemBody.tsx
  client/src/components/Drinks/DrinksList/drinkscontent/drinksitem/DrinksItemBox.tsx
  client/src/components/Drinks/DrinksList/drinkscontent/drinksitem/DrinksItemLevel.tsx
Labels: FE, design

#172 [FE] fix: 사용자 프로필 이미지 관련 작업
  client/src/assets/img/brandon-green-21jzeYnvZTY-unsplash.jpg
  client/src/components/MyPage/MyPageInfoContent.tsx
  client/src/components/layout/Header/UserNav.tsx
Labels: bug, FE

#173 [FE] design: favicon 수정, logo 추가
  client/public/favicon.ico
  client/public/index.html
  client/src/assets/img/logo/withskey_b.png
  client/src/assets/img/logo/withskey_w.png
  client/src/components/UI/LogoText.tsx
Labels: FE, design

#174 [FE] feat: SignUp 페이지 게스트 로그인 모드 추가
  client/src/assets/img/victor-hughes-OSLyizm8ovY-unsplash.jpg
  client/src/components/MyPage/MyPageBoard.tsx
  client/src/components/MyPage/MyPageContent.tsx
  client/src/components/MyPage/MyPageDrinks.tsx
  client/src/components/MyPage/MyPageInfoContent.tsx
  client/src/components/SignUp/SignUpButton.tsx
  client/src/components/SignUp/SignUpContent.tsx
  client/src/components/SignUp/SignUpTitle.tsx
  client/src/components/layout/Header/UserNav.tsx
Labels: enhancement, FE, design

#182 [FE] refactor: customAxios 설정 및 MyPage 추가 작업
  client/src/App.tsx
  client/src/api/customAxios.ts
  client/src/components/Article/ArticleDetail/ArticleDetailContent.tsx
  client/src/components/Article/ArticleDetail/ArticleDetails.tsx
  client/src/components/Board/BoardCreateInput.tsx
  client/src/components/Board/BoardLikes.tsx
  client/src/components/Drinks/DrinksList/MainDrinks.tsx
  client/src/components/Drinks/DrinksList/drinkscontent/drinksitem/drinksitembox/DrinksItemLikes.tsx
  client/src/components/MyPage/MyPageBoardBox.tsx
  client/src/components/MyPage/MyPageBoardComment.tsx
  client/src/components/MyPage/MyPageContentBar.tsx
  client/src/components/MyPage/MyPageDrinkLike.tsx
  client/src/components/MyPage/MyPageDrinksBox.tsx
  client/src/components/MyPage/MyPageInfoContent.tsx
  client/src/components/MyPage/MyPageInfoItem.tsx
  client/src/components/Tags/MainTags.tsx
  client/src/components/UI/Comment/Comment.tsx
  client/src/components/UI/Comment/CommentInput.tsx
  client/src/components/UI/Comment/CommentModal.tsx
  client/src/pages/BoardCreate.tsx
  client/src/pages/BoardDetail.tsx
  client/src/pages/BoardList.tsx
  client/src/pages/DrinksDetail.tsx
  client/src/pages/MyPage.tsx
  client/src/util/convertTime.ts
Labels: enhancement, FE, design

#183 [FE] design: Main Page 재구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/img/WithsKey.png
  client/src/assets/img/bar.jpg
  client/src/components/Main/MainBannerContent.tsx
  client/src/components/Main/MainDrinksContent.tsx
  client/src/components/Main/MainTagsContent.tsx
  client/src/components/Main/MainTextContent.tsx
  client/src/components/Main/MainVisual.tsx
  client/src/components/Main/mainbannercontent/MainBannerContentArrow.tsx
  client/src/components/Main/mainbannercontent/MainBannerContentImg.tsx
  client/src/components/Main/mainbannercontent/MainBannerContentTitle.tsx
  client/src/components/Main/maindrinkscontent/MainDrinksContentDrink.tsx
  client/src/components/Main/maindrinkscontent/MainDrinksContentDrinks.tsx
  client/src/components/Main/maindrinkscontent/MainDrinksContentTitle.tsx
  client/src/components/Main/maintagscontent/MainTagsContentImg.tsx
  client/src/components/Main/maintagscontent/MainTagsContentTag.tsx
  client/src/components/Main/maintagscontent/MainTagsContentTags.tsx
  client/src/components/Main/maintextcontent/MainTextContentImg.tsx
  client/src/components/Main/maintextcontent/MainTextContentTitle.tsx
  client/src/components/Main2/MainArrowButton.tsx
  client/src/components/Main2/MainContent.tsx
  client/src/components/Main2/MainContentBody.tsx
  client/src/components/Main2/MainContentInfo.tsx
  client/src/components/Main2/MainDontMove.tsx
  client/src/components/Main2/MainMain.tsx
  client/src/components/Main2/MainSuggestDrinksBox.tsx
  client/src/components/Main2/maincontentinfo/MainContentInfoImg.tsx
  client/src/components/Main2/maincontentinfo/MainContentInfoText.tsx
  client/src/components/Main2/mainsuggestdrinksbox/MainSuggestDrink.tsx
  client/src/components/Main2/mainsuggestdrinksbox/MainSuggestDrinks.tsx
  client/src/components/Main2/mainsuggesttagsbox/MainSuggestImg.tsx
  client/src/components/Main2/mainsuggesttagsbox/MainSuggestTag.tsx
  client/src/components/Main2/mainsuggesttagsbox/MainSuggestTags.tsx
  client/src/components/layout/MainLayout.tsx
  client/src/pages/Main.tsx
Labels: enhancement, FE, design

#187 [FE] desgin: Main Page Drknks, Tags CSS 수정
  client/src/assets/img/bar.jpg
  client/src/assets/img/jackdaniels(low).jpg
  client/src/components/Drinks/DrinksDetail/drinksdetailcontent/DrinksDetailWiths.tsx
  client/src/components/Main/MainDrinksContent.tsx
  client/src/components/Main/MainTagsContent.tsx
  client/src/components/Main/MainTextContent.tsx
  client/src/components/Main/MainVisual.tsx
  client/src/components/Main/maindrinkscontent/MainDrinksContentDrinks.tsx
  client/src/components/Main/maindrinkscontent/MainDrinksContentTitle.tsx
  client/src/components/Main/maintagscontent/MainTagsContentImg.tsx
  client/src/components/Main/maintagscontent/MainTagsContentTag.tsx
  client/src/components/Main/maintagscontent/MainTagsContentTags.tsx
Labels: FE, design

#190 [FE] design: Main Page Carousel
  client/src/assets/icon/arrow-01.png
  client/src/assets/icon/arrow-02.png
  client/src/components/Main/MainBannerContent.tsx
  client/src/components/Main/MainDontMove.tsx
  client/src/components/Main/maintagscontent/MainTagsContentTags.tsx
  client/src/components/Main2/MainArrowButton.tsx
  client/src/components/Main2/MainContent.tsx
  client/src/components/Main2/MainContentBody.tsx
  client/src/components/Main2/MainContentInfo.tsx
  client/src/components/Main2/MainMain.tsx
  client/src/components/Main2/MainSuggestDrinksBox.tsx
  client/src/components/Main2/maincontentinfo/MainContentInfoImg.tsx
  client/src/components/Main2/maincontentinfo/MainContentInfoText.tsx
  client/src/components/Main2/mainsuggestdrinksbox/MainSuggestDrink.tsx
  client/src/components/Main2/mainsuggestdrinksbox/MainSuggestDrinks.tsx
  client/src/components/Main2/mainsuggesttagsbox/MainSuggestImg.tsx
  client/src/components/Main2/mainsuggesttagsbox/MainSuggestTag.tsx
  client/src/components/Main2/mainsuggesttagsbox/MainSuggestTags.tsx
  client/src/components/layout/MainLayout.tsx
Labels: FE, design

#193 [FE] design: Article Detail Menu 클릭 시 배경색 고정
  client/src/App.tsx
  client/src/components/Article/ArticleDetail/ArticleDetailMenu.tsx
  client/src/components/Article/ArticleDetail/ArticleDetails.tsx
  client/src/components/Article/ArticleDetail/articledetailcontent/ArticleDetailBody.tsx
  client/src/components/Article/ArticleDetail/articledetailmenu/ArticleDetailMenuItem.tsx
  client/src/pages/ArticleDetail.tsx
Labels: FE, design

#195 [FE] fix: DrinksList TagList Swiper 적용
  client/package-lock.json
  client/package.json
  client/src/components/Drinks/DrinksList/DrinksInfo.tsx
  client/src/components/Drinks/DrinksList/drinkscontent/DrinksItem.tsx
  client/src/components/Drinks/DrinksList/drinkscontent/drinksitem/drinksitembox/DrinksItemLikes.tsx
  client/src/components/Drinks/DrinksList/drinksinfo/DrinksSearch.tsx
  client/src/components/Drinks/DrinksList/drinksinfo/DrinksTagList.tsx
  client/yarn.lock
Labels: enhancement, FE

#196 [FE] design: Main Header Transparent 변경
  client/package-lock.json
  client/src/components/Article/ArticleDetail/articledetailmenu/ArticleDetailMenuItem.tsx
  client/src/components/Drinks/DrinksList/drinksinfo/DrinksTagList.tsx
  client/src/components/Main/MainBannerContent.tsx
  client/src/components/Main/MainTextContent.tsx
  client/src/components/Main/MainVisual.tsx
  client/src/components/Main/maintagscontent/MainTagsContentImg.tsx
  client/src/components/Main/maintextcontent/MainTextContentImg.tsx
  client/src/global-style.tsx
  client/yarn.lock
Labels: FE, design
